services:
    _defaults:
        autowire: true
        public: false

    avariya.middleware.request_id:
        class: Avariya\RequestIdBundle\Middleware\RequestIdMiddleware
        tags:
          - { name: csa_guzzle.middleware, alias: request_id_middleware }
        arguments: ['@Qandidate\Stack\UuidRequestIdGenerator', "@request_stack"]

    Qandidate\Stack\UuidRequestIdGenerator: ~
    Qandidate\Stack\RequestIdGenerator:
        alias: Qandidate\Stack\UuidRequestIdGenerator