services:
    _defaults:
        autowire: true
        public: false

    Avariya\RequestIdBundle\Middleware\RequestIdMiddleware: ~
    avariya.middleware.request_id:
        alias: Avariya\RequestIdBundle\Middleware\RequestIdMiddleware

    Qandidate\Stack\UuidRequestIdGenerator: ~
    Qandidate\Stack\RequestIdGenerator:
        alias: Qandidate\Stack\UuidRequestIdGenerator