services:
    _defaults:
        autowire: true
        public: false

    Avariya\Listener\ExtendKernelListener:
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }