services:
    _defaults:
        public: false

    Qandidate\Stack\RequestId\MonologProcessor:
        arguments:
          - '%avariya.request_id.header%'
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
          - { name: monolog.processor }