services:
    _defaults:
        autowire: true
        public: false

    Qandidate\Stack\UuidRequestIdGenerator: ~
    Qandidate\Stack\RequestIdGenerator:
        alias: Qandidate\Stack\UuidRequestIdGenerator